baseurl: "https://2016.elm-conf.us/"
languageCode: "en-us"
title: "elm-conf 2016"
theme: "elm-conf"
taxonomies:
  sponsor_levels: "sponsor_levels"
params:
  date: September 15, 2016
  location: St. Louis, Missouri

  # CFP info
  cfp_start: 'June 1, 2016'
  cfp_end: 'June 30, 2016'
  cfp_notify: 'July 8, 2016'
  cfp_link: 'https://www.papercall.io/elm-conf-us-2016'

  # Ticketing Info
  ticket_link: 'https://ti.to/strange-loop/2016'

  # Contact
  email: elm-conf@thestrangeloop.com
  twitter: ElmConf
  twitter_hashtag: "#ElmConf"
